# Generated by Django 4.1.7 on 2023-03-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_total_rental_alter_book_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_rental',
            new_name='total_retal',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('availabl', 'available'), ('retal', 'retal'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
